import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Expense Tracker App",
  description: "Generated by panpasa",
  icons: {
    icon: '/logoEx.png', // avicon path ถูกต้องแล้ว
    shortcut: '/logoEx.png',
    apple: '/logoEx.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen relative`}
      >
        {/* พื้นหลัง GIF */}
        <div
          className="absolute inset-0 z-0"
          style={{
            backgroundImage: 'url("/assets/gif1.gif")', // เส้นทางของ GIF
            backgroundSize: 'cover',  // ขยาย GIF ให้เต็มหน้าจอ
            backgroundPosition: 'center',  // จัดตำแหน่ง GIF ให้อยู่กลาง
            backgroundRepeat: 'no-repeat',  // ป้องกันไม่ให้ GIF ซ้ำ
          }}
        />

        {/* เนื้อหาของเว็บไซต์ */}
        <div className="relative z-10 min-h-screen">
          {children}
        </div>
      </body>
    </html>
  );
}
